/**
 * [TRIfA], Java part of Tox Reference Implementation for Android
 * Copyright (C) 2017 Zoff <zoff@zoff.cc>
 * <p>
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation.
 * <p>
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * <p>
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA.
 */

package com.zoffcc.applications.trifa;

import org.khandaq.messenger.R;

import android.content.Context;
import android.content.Intent;
import android.os.AsyncTask;
import android.os.Bundle;
import android.text.TextUtils;
import android.util.Log;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.google.android.material.textfield.TextInputEditText;

import static com.zoffcc.applications.trifa.TRIFAGlobals.PREF__DB_secrect_key__user_hash;

public class CheckPasswordActivity extends AppCompatActivity
{
    private static final String TAG = "trifa.CheckPasswordActy";

    // UI references.
    private TextInputEditText mPasswordView1;
    private View mLoginFormView;
    private ProgressBar mProgressView;
    private UnlockTask mUnlockTask;

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        Log.i(TAG, "onCreate");

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_check_password);

        mPasswordView1 = findViewById(R.id.password_1_c);
        mLoginFormView = findViewById(R.id.login_form_2);
        mProgressView = findViewById(R.id.login_progress_2);
        if (mPasswordView1 == null)
        {
            Log.e(TAG, "password field missing from layout");
            Toast.makeText(this, R.string.wrong_credentials_error, Toast.LENGTH_LONG).show();
            finish();
            return;
        }
        mPasswordView1.requestFocus();
        mPasswordView1.setOnEditorActionListener(new TextView.OnEditorActionListener()
        {
            @Override
            public boolean onEditorAction(TextView textView, int id, KeyEvent keyEvent)
            {
                return true;
            }
        });

        Button SignInButton = (Button) findViewById(R.id.set_button_2);
        SignInButton.setOnClickListener(new OnClickListener()
        {
            @Override
            public void onClick(View view)
            {
                Log.i(TAG, "unlock:002");
                attemptUnlock_new(view.getContext(), false, mPasswordView1.getText().toString());
            }
        });

        // KHANDAQ (#9): Back on the login screen — single-profile app has nowhere to navigate back to,
        // so minimise the app instead of leaving it sitting unlocked-but-visible.
        final View backButton = findViewById(R.id.login_back);
        if (backButton != null)
        {
            backButton.setOnClickListener(v -> moveTaskToBack(true));
        }

        // KHANDAQ (#5a): recovery entry point for a forgotten password.
        final View forgotLink = findViewById(R.id.forgot_password_link);
        if (forgotLink != null)
        {
            forgotLink.setOnClickListener(v -> showRecoveryDialog());
        }

        try
        {
            /* if the database secret key is saved in preferences, it means the user did NOT want to set a password.
             * and for our purpose we can also skip the password enter screen
             */
            String DB_secrect_key__tmp = DbSecretKeyStorage.loadAutoGeneratedKey(this);
            if (TextUtils.isEmpty(DB_secrect_key__tmp))
            {
                DB_secrect_key__tmp = DbSecretKeyStorage.resolveDbSecretKey(this);
            }

            Log.i(TAG, "001");

            // KHANDAQ (session persistence): a manual-password user who is still LOGGED IN (never
            // pressed «Выйти») must not be re-asked the password just because the OS killed the idle
            // process — the app-lock PIN is the idle gate. The Keystore-wrapped last-working key is
            // probed against the real DB, so a wrong key can never auto-unlock by construction.
            if (!TextUtils.isEmpty(DB_secrect_key__tmp)
                    && (!DbSecretKeyStorage.prefersManualPasswordUnlock(this)
                        || DbSecretKeyStorage.isSessionLoggedIn(this)))
            {
                Log.i(TAG, "auto_generated_password:true");
                Log.i(TAG, "003");
                attemptUnlock_new(this, true, DB_secrect_key__tmp);
                Log.i(TAG, "004");
            }
        }
        catch (Exception e)
        {
            Log.i(TAG, "EE:002");
        }
        Log.i(TAG, "006");
    }

    // KHANDAQ (#5a): explain why a lost password can't be recovered (data is password-encrypted) and
    // offer to start over. The profile is single-instance, so "start over" wipes the current DB.
    private void showRecoveryDialog()
    {
        new androidx.appcompat.app.AlertDialog.Builder(this)
                .setTitle(R.string.recovery_dialog_title)
                .setMessage(R.string.recovery_dialog_message)
                .setPositiveButton(R.string.recovery_create_new, (d, w) -> confirmWipeAndRestart())
                .setNegativeButton(android.R.string.cancel, null)
                .show();
    }

    private void confirmWipeAndRestart()
    {
        new androidx.appcompat.app.AlertDialog.Builder(this)
                .setTitle(R.string.recovery_confirm_wipe_title)
                .setMessage(R.string.recovery_confirm_wipe_message)
                .setPositiveButton(R.string.recovery_confirm_wipe_yes, (d, w) -> performRecoveryWipe())
                .setNegativeButton(android.R.string.cancel, null)
                .show();
    }

    // KHANDAQ (#5a): mirror ProfileDetailsActivity.performProfileWipe — flag a pending wipe, then end
    // the process so StartMainActivityWrapper deletes the encrypted DB in a fresh process (no open
    // file handles) and routes into the onboarding (create / import) flow. Existing DB gone → set_pattern.
    private void performRecoveryWipe()
    {
        try
        {
            MainActivity.manually_log_out();
        }
        catch (Exception ignored)
        {
        }
        try
        {
            android.preference.PreferenceManager.getDefaultSharedPreferences(this).edit()
                    .putBoolean(ProfileDetailsActivity.PREF__pending_profile_wipe, true)
                    .putBoolean("PW_SET_SCREEN_DONE", false)
                    .commit();
            TRIFAGlobals.PREF__DB_secrect_key__user_hash = "";
        }
        catch (Exception ignored)
        {
        }
        try
        {
            finishAffinity();
        }
        catch (Exception ignored)
        {
        }
        System.exit(0);
    }

    private void attemptUnlock_new(Context c, boolean auto_generated_pass, String pass)
    {
        if (mUnlockTask != null)
        {
            return;
        }

        if (mPasswordView1 != null)
        {
            mPasswordView1.setError(null);
        }

        if (TextUtils.isEmpty(pass))
        {
            if (mPasswordView1 != null)
            {
                mPasswordView1.setError(getString(R.string.set_password_message_empty));
                mPasswordView1.requestFocus();
            }
            return;
        }

        if (auto_generated_pass)
        {
            finishUnlock(pass);
            return;
        }

        showProgress(true);
        mUnlockTask = new UnlockTask(c);
        mUnlockTask.execute(pass);
    }

    private void finishUnlock(String try_password_hash)
    {
        if (TextUtils.isEmpty(try_password_hash))
        {
            if (mPasswordView1 != null)
            {
                mPasswordView1.setError(getString(R.string.wrong_credentials_error));
                mPasswordView1.requestFocus();
            }
            return;
        }

        PREF__DB_secrect_key__user_hash = try_password_hash;

        // KHANDAQ (session persistence): unlock succeeded — mark the session logged in (re-arms
        // after an explicit logout; also reached by the auto-unlock path for skip-password users).
        DbSecretKeyStorage.setSessionLoggedIn(this, true);

        Intent main_act = new Intent(this, MainActivity.class);
        startActivity(main_act);
        finish();
    }

    private void showProgress(final boolean show)
    {
        if (mLoginFormView == null || mProgressView == null)
        {
            return;
        }

        mLoginFormView.setVisibility(show ? View.GONE : View.VISIBLE);
        mProgressView.setVisibility(show ? View.VISIBLE : View.GONE);
    }

    private class UnlockTask extends AsyncTask<String, Void, String>
    {
        private final Context context;

        UnlockTask(Context context)
        {
            this.context = context.getApplicationContext();
        }

        @Override
        protected String doInBackground(String... params)
        {
            if (params == null || params.length == 0)
            {
                return null;
            }

            return DbSecretKeyStorage.unlockManualPasswordHash(context, params[0]);
        }

        @Override
        protected void onPostExecute(String try_password_hash)
        {
            mUnlockTask = null;
            showProgress(false);

            if (try_password_hash == null)
            {
                if (mPasswordView1 != null)
                {
                    mPasswordView1.setError(getString(R.string.wrong_credentials_error));
                    mPasswordView1.requestFocus();
                }
                return;
            }

            // KHANDAQ (audit #8): the user just TYPED the profile password — that is an authentication,
            // so the cold-start gate must not ask for the PIN on top of it (one gate, as before).
            // Only this path marks it: the auto-unlock in onCreate() takes no user input at all and is
            // exactly the hole the cold-start gate exists to cover.
            AppLockHelper.markProcessUnlocked();
            finishUnlock(try_password_hash);
        }

        @Override
        protected void onCancelled()
        {
            mUnlockTask = null;
            showProgress(false);
        }
    }

    /*
    @Override
    public void onBackPressed()
    {
        // super.onBackPressed();
        // do nothing!!
    }
     */
}
