package com.zoffcc.applications.trifa;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Build;
import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Base64;
import android.util.Log;

import androidx.preference.PreferenceManager;

import java.nio.charset.StandardCharsets;
import java.security.KeyStore;
import java.security.SecureRandom;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/**
 * Stores auto-generated DB keys in Android Keystore instead of plaintext prefs.
 */
public final class DbSecretKeyStorage
{
    private static final String TAG = "trifa.DbSecretKeyStorage";
    private static final String PREFS_AUTO_KEY = "DB_secrect_key";
    private static final String PREFS_MIGRATED = "DB_secrect_key_keystore_migrated";
    private static final String KEYSTORE_ALIAS = "khandaq_db_auto_key";
    private static final String PREFS_ENC_BLOB = "DB_secrect_key_enc";
    private static final String PREFS_ENC_IV = "DB_secrect_key_iv";

    private DbSecretKeyStorage()
    {
    }

    static void saveAutoGeneratedKey(final Context context, final String plaintextKey)
    {
        if (context == null || plaintextKey == null || plaintextKey.isEmpty())
        {
            return;
        }

        try
        {
            final SecretKey secretKey = getOrCreateKey();
            final Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            cipher.init(Cipher.ENCRYPT_MODE, secretKey);
            final byte[] iv = cipher.getIV();
            final byte[] encrypted = cipher.doFinal(plaintextKey.getBytes(StandardCharsets.UTF_8));

            final SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(context);
            prefs.edit()
                    .putString(PREFS_ENC_BLOB, Base64.encodeToString(encrypted, Base64.NO_WRAP))
                    .putString(PREFS_ENC_IV, Base64.encodeToString(iv, Base64.NO_WRAP))
                    .putBoolean(PREFS_MIGRATED, true)
                    .remove(PREFS_AUTO_KEY)
                    .commit();
        }
        catch (Exception e)
        {
            Log.w(TAG, "keystore save failed, keeping legacy pref: " + e.getMessage());
            PreferenceManager.getDefaultSharedPreferences(context).edit()
                    .putString(PREFS_AUTO_KEY, plaintextKey)
                    .commit();
        }
    }

    static String loadAutoGeneratedKey(final Context context)
    {
        if (context == null)
        {
            return null;
        }

        final SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(context);

        migratePlaintextToKeystore(context, prefs);

        try
        {
            final String enc = prefs.getString(PREFS_ENC_BLOB, null);
            final String ivB64 = prefs.getString(PREFS_ENC_IV, null);
            if (enc == null || ivB64 == null)
            {
                return prefs.getString(PREFS_AUTO_KEY, null);
            }

            final SecretKey secretKey = getOrCreateKey();
            final Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            cipher.init(Cipher.DECRYPT_MODE, secretKey,
                    new GCMParameterSpec(128, Base64.decode(ivB64, Base64.NO_WRAP)));
            final byte[] plain = cipher.doFinal(Base64.decode(enc, Base64.NO_WRAP));
            return new String(plain, StandardCharsets.UTF_8);
        }
        catch (Exception e)
        {
            Log.w(TAG, "keystore load failed: " + e.getMessage());
            return prefs.getString(PREFS_AUTO_KEY, null);
        }
    }

    private static void migratePlaintextToKeystore(final Context context, final SharedPreferences prefs)
    {
        if (prefs.getBoolean(PREFS_MIGRATED, false))
        {
            return;
        }

        final String legacy = prefs.getString(PREFS_AUTO_KEY, null);
        if (legacy != null && !legacy.isEmpty())
        {
            saveAutoGeneratedKey(context, legacy);
        }
    }

    private static SecretKey getOrCreateKey() throws Exception
    {
        final KeyStore ks = KeyStore.getInstance("AndroidKeyStore");
        ks.load(null);

        if (!ks.containsAlias(KEYSTORE_ALIAS))
        {
            final KeyGenerator kg = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore");
            final KeyGenParameterSpec spec = new KeyGenParameterSpec.Builder(
                    KEYSTORE_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT | KeyProperties.PURPOSE_DECRYPT)
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setRandomizedEncryptionRequired(true)
                    .build();
            kg.init(spec);
            kg.generateKey();
        }

        return (SecretKey) ks.getKey(KEYSTORE_ALIAS, null);
    }

    /** PBKDF2 with per-device salt; legacy SHA-256 remains for migration. */
    static String deriveManualPasswordHash(final Context context, final String password) throws Exception
    {
        final SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(context);
        String saltB64 = prefs.getString("DB_secret_salt", null);

        if (saltB64 == null)
        {
            final byte[] salt = new byte[16];
            new SecureRandom().nextBytes(salt);
            saltB64 = Base64.encodeToString(salt, Base64.NO_WRAP);
            prefs.edit().putString("DB_secret_salt", saltB64).commit();
        }

        final byte[] salt = Base64.decode(saltB64, Base64.NO_WRAP);
        final javax.crypto.spec.PBEKeySpec spec = new javax.crypto.spec.PBEKeySpec(
                password.toCharArray(), salt, 120_000, 256);
        final javax.crypto.SecretKeyFactory skf =
                javax.crypto.SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256");
        final byte[] derived = skf.generateSecret(spec).getEncoded();
        return TrifaSetPatternActivity.bytesToString(derived);
    }

    static String unlockManualPasswordHash(final Context context, final String password)
    {
        try
        {
            final SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(context);
            if (prefs.contains("DB_secret_salt"))
            {
                return deriveManualPasswordHash(context, password);
            }
        }
        catch (Exception e)
        {
            Log.w(TAG, "PBKDF2 failed, trying legacy: " + e.getMessage());
        }

        try
        {
            return TrifaSetPatternActivity.bytesToString(
                    TrifaSetPatternActivity.sha256(TrifaSetPatternActivity.StringToBytes2(password)));
        }
        catch (Exception e)
        {
            return null;
        }
    }
}
