#!/usr/bin/env bash
# Build Antidote iOS (Zoxcore fork) — upstream as-is, simulator .app
# Note: Xcode 15+ may fail on Pods/libsodium alignment — use fetch-ios-antidote.sh for IPA
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${KHANDAQ_IOS_SRC:-$ROOT/khandaq-ios}"
DIST="$ROOT/dist/ios"
SCHEME="${IOS_SCHEME:-Antidote}"

command -v xcodebuild >/dev/null || { echo "Xcode required"; exit 1; }
[[ -d "$SRC" ]] || { echo "Missing $SRC"; exit 1; }

mkdir -p "$DIST"
cd "$SRC"

# KHANDAQ (audit 2026-08-21, K-07): every CocoaPods/fastlane invocation goes through Bundler, so the
# committed Gemfile.lock — not whatever Homebrew put on this Mac — decides the versions.
#
# BUNDLE_GEMFILE is set EXPLICITLY rather than left to the working directory, and that is not
# belt-and-braces: khandaq-ios/local_pod_repo/objcTox carries its own Gemfile pinning
# `cocoapods '~> 1.0.1'` with no lockfile, so a bare `bundle exec` run from anywhere under it would
# silently downgrade CocoaPods by fifteen minor versions.
export BUNDLE_GEMFILE="$SRC/Gemfile"

command -v bundle >/dev/null || {
  echo "Bundler required: gem install bundler"; exit 1; }
# activesupport 7.2.3.2 in Gemfile.lock needs Ruby >= 3.1. Checked here rather than pinned in a
# .ruby-version, because pinning an exact patch release that is not installed on the release Mac
# turns a working build into a hard failure, while a floor only replaces a confusing error with a
# clear one. (A `ruby` directive in the Gemfile would have the same effect, but it also changes what
# Bundler records in Gemfile.lock, and that lock must not be regenerated outside a reviewed commit.)
ruby -e 'exit(Gem::Version.new(RUBY_VERSION) >= Gem::Version.new("3.1"))' || {
  echo "Ruby >= 3.1 required (Gemfile.lock resolves activesupport 7.2.x); found $(ruby -v)"; exit 1; }
bundle check >/dev/null 2>&1 || bundle install

# KHANDAQ (audit 2026-08-21): this used to be `if [[ ! -f Podfile.lock ]]`, which meant it never ran:
# Podfile.lock IS committed, Pods/ is gitignored and Antidote.xcworkspace is generated by pod
# install and not committed either — so from a clean clone the install was skipped and the script
# died two lines later on the missing workspace. Key on the artefacts that are actually absent.
if [[ ! -d Pods || ! -f Pods/Manifest.lock ]]; then
  echo "==> bundle exec pod install..."
  bundle exec pod install
fi

[[ -d Antidote.xcworkspace ]] || { echo "Antidote.xcworkspace missing after pod install"; exit 1; }

SIM_ID=$(xcrun simctl list devices available -j 2>/dev/null | python3 -c "
import json,sys
data=json.load(sys.stdin)
for r in data.get('devices',{}).values():
  for d in r:
    if d.get('isAvailable') and 'iPhone' in d.get('name',''):
      print(d['udid']); raise SystemExit
" 2>/dev/null || true)
DEST="${IOS_DESTINATION:-platform=iOS Simulator,id=${SIM_ID}}"
echo "==> xcodebuild ($SCHEME, $DEST)..."
xcodebuild \
  -workspace Antidote.xcworkspace \
  -scheme "$SCHEME" \
  -configuration Release \
  -destination "$DEST" \
  -derivedDataPath "$SRC/build/DerivedData" \
  CODE_SIGNING_ALLOWED=NO \
  build 2>&1 | tee "$DIST/xcodebuild.log"

APP=$(find "$SRC/build/DerivedData" -name '*.app' -path '*Release-iphonesimulator*' | head -1)
if [[ -n "$APP" && -d "$APP" ]]; then
  rm -rf "$DIST/Antidote.app"
  cp -a "$APP" "$DIST/Antidote.app"
  ( cd "$DIST" && zip -qr Antidote-simulator.zip Antidote.app )
  echo "iOS simulator build OK: $DIST/Antidote-simulator.zip"
else
  echo "Build finished but .app not found — see $DIST/xcodebuild.log"
  exit 1
fi
